import defaultTheme, { commonColorsPalette } from './default';
import { GrafanaThemeType, GrafanaTheme } from '@grafana/data';

const basicColors = {
  ...commonColorsPalette,
  black: '#000000',
  white: '#ffffff',
  dark6: '#262628',
  dark7: '#292a2d',
  dark8: '#2f2f32',
  dark9: '#343436',
  dark10: '#424345',
  grayBlue: '#212327',
  blueBase: '#3274d9',
  blueShade: '#1f60c4',
  blueLight: '#00a8e6',
  blueFaint: '#041126',
  redBase: '#ff2a2a',
  redShade: '#b00000',
  greenBase: '#299c46',
  greenShade: '#23843b',
  yellow: '#ff851b',
  orangeBase: '#ff7941',
  orangeShade: '#fd6222',
  purple: '#9954bb',
  variable: '#32d1df',
};

const darkTheme: GrafanaTheme = {
  ...defaultTheme,
  type: GrafanaThemeType.Dark,
  isDark: true,
  isLight: false,
  name: 'Grafana Dark',
  colors: {
    ...basicColors,
    inputBlack: '#09090b',
    brandPrimary: basicColors.orangeBase,
    brandSuccess: basicColors.greenBase,
    brandWarning: basicColors.orangeBase,
    brandDanger: basicColors.redBase,
    queryRed: basicColors.redBase,
    queryGreen: '#74e680',
    queryPurple: '#fe85fc',
    queryKeyword: '#66d9ef',
    queryOrange: basicColors.orangeBase,
    // Status colors
    online: '#01a64f',
    warn: '#f79520',
    critical: '#ec2128',
    // Scaffolding
    bodyBg: basicColors.gray7,
    pageBg: basicColors.gray7,
    body: basicColors.gray1,
    text: basicColors.gray8,
    textStrong: basicColors.dark2,
    textWeak: basicColors.gray8,
    textFaint: basicColors.gray4,
    textEmphasis: basicColors.dark5,
    // Link colors
    link: basicColors.gray1,
    linkDisabled: basicColors.gray2, // lighten(link, 30%);
    linkHover: basicColors.orangeBase,
    linkExternal: basicColors.blueBase,
    headingColor: basicColors.gray4,
    pageHeaderBorder: basicColors.dark9,
    panelBg: basicColors.white,

    // Next-gen forms functional colors
    formLabel: basicColors.dark9,
    formDescription: basicColors.gray70,
    formLegend: basicColors.gray85,
    formInputBg: basicColors.white,
    formInputBgDisabled: basicColors.gray2,
    formInputBorder: basicColors.gray8,
    formInputBorderHover: basicColors.gray33,
    formInputBorderActive: basicColors.blue95,
    formInputBorderInvalid: basicColors.redBase,
    formInputText: basicColors.gray1,
    formInputPlaceholderText: basicColors.gray33,
    formInputDisabledText: basicColors.gray4,
    formInputTextStrong: basicColors.gray85,
    formInputTextWhite: basicColors.white,
    formFocusOutline: basicColors.blueShade,
    formValidationMessageText: basicColors.white,
    formValidationMessageBg: basicColors.red88,
    formSwitchBg: basicColors.gray25,
    formSwitchBgActive: basicColors.blueLight,
    formSwitchBgHover: basicColors.gray33,
    formSwitchBgActiveHover: basicColors.blueBase,
    formSwitchBgDisabled: basicColors.gray25,
    formSwitchDot: basicColors.gray15,
    formCheckboxBg: basicColors.dark5,
    formCheckboxBgChecked: basicColors.blueLight,
    formCheckboxBgCheckedHover: basicColors.blueBase,
    formCheckboxCheckmark: basicColors.gray25,
  },
  background: {
    dropdown: basicColors.white,
    scrollbar: basicColors.gray5,
    scrollbar2: basicColors.gray5,
    pageHeader: `linear-gradient(90deg, ${basicColors.gray5}, ${basicColors.gray3})`,
  },
  shadow: {
    pageHeader: `inset 0px -4px 14px ${basicColors.dark3}`,
  },
};

export default darkTheme;
